name: On Push

on:
  push:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with: 
          python-version: '3.12'
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      
      - name: Check for uv lock file
        run: uv lock --check
      
      - name: Linting
        run: uv run --group lint ruff check .

      - name: Testing
        run: uv run --group test python -Bm pytest -p no:cacheprovider